import Foundation

/// 一条表情/符号条目。纯值类型。
public struct EmojiDef: Identifiable, Hashable {
    public let character: String
    /// 英文名（搜索主键）。
    public let name: String
    /// 中文关键词（空格分隔）。
    public let zh: String
    public let category: String

    public var id: String { character }
}

/// 表情与符号目录。内置精选集（可搜索、无网络、无依赖）。
/// 搜索排序：中词精确 > 英名前缀 > 英名包含 > 模糊（封顶）。
public enum EmojiCatalog {
    /// 分类稳定 id（分区 id 沿用；显示名随语言）。
    public static let categories = ["smileys", "people", "animals", "food", "activity", "travel", "objects", "symbols", "type"]

    public static let categoryNames: [String: (zh: String, en: String)] = [
        "smileys": ("表情", "Smileys"),
        "people": ("人物", "People"),
        "animals": ("动物", "Animals"),
        "food": ("食物", "Food"),
        "activity": ("活动", "Activity"),
        "travel": ("旅行", "Travel"),
        "objects": ("物品", "Objects"),
        "symbols": ("符号", "Symbols"),
        "type": ("键位与排版", "Type & Symbols"),
    ]

    public static func categoryName(_ id: String) -> String {
        guard let name = categoryNames[id] else { return id }
        return L10n.t(name.zh, name.en)
    }

    public static let all: [EmojiDef] = build()

    public struct Scored {
        let def: EmojiDef
        let score: Int
    }

    /// 搜索：中文关键词命中优先，其次英文名。
    public static func search(_ query: String, limit: Int = 80) -> [EmojiDef] {
        let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard !trimmed.isEmpty else {
            // 空查询：每类取前若干，浏览态
            var result: [EmojiDef] = []
            for category in categories {
                result += all.filter { $0.category == category }.prefix(24)
            }
            return Array(result.prefix(limit))
        }
        return all.compactMap { def -> Scored? in
            let score = rank(query: trimmed, def: def)
            guard score > 0 else { return nil }
            return Scored(def: def, score: score)
        }
        .sorted {
            $0.score != $1.score ? $0.score > $1.score
                : $0.def.name < $1.def.name
        }
        .prefix(limit)
        .map(\.def)
    }

    public static func rank(query: String, def: EmojiDef) -> Int {
        let name = def.name.lowercased()
        if name == query { return 300 }
        if def.zh.lowercased().contains(query) {
            // 中文词整词命中强于英文前缀
            return def.zh.lowercased().split(separator: " ").contains { $0 == query } ? 250 : 150
        }
        if name.hasPrefix(query) { return 120 }
        if name.split(separator: " ").contains(where: { $0.hasPrefix(query) }) { return 100 }
        if name.contains(query) { return 80 }
        if let fuzzy = FuzzyMatch.score(query: query, target: name) {
            return min(fuzzy, 59)
        }
        return 0
    }

    // MARK: - 数据

    private static func build() -> [EmojiDef] {
        var list: [EmojiDef] = []

        // 表情 Smileys
        let smileys: [(String, String, String)] = [
            ("😀", "grinning", "笑 高兴 开心"),
            ("😃", "smiley", "笑 高兴 开心"),
            ("😄", "smile", "笑 开心 眼睛"),
            ("😁", "grin", "露齿笑 开心"),
            ("😆", "laughing", "大笑 哈哈"),
            ("😅", "sweat smile", "尴尬 汗 笑"),
            ("🤣", "rofl", "笑翻 打滚 哈哈"),
            ("😂", "joy", "笑哭 高兴 好笑"),
            ("🙂", "slightly smiling", "微笑"),
            ("🙃", "upside down", "倒脸 无语 玩笑"),
            ("😉", "wink", "眨眼 俏皮"),
            ("😊", "blush", "害羞 微笑 脸红"),
            ("😇", "innocent", "天使 无辜"),
            ("🥰", "smiling hearts", "爱 喜欢 心"),
            ("😍", "heart eyes", "爱 惊叹 喜欢"),
            ("🤩", "star struck", "星星眼 惊叹"),
            ("😘", "kiss", "亲亲 飞吻"),
            ("😗", "kissing", "亲亲"),
            ("😚", "kissing closed eyes", "亲亲"),
            ("😙", "kissing smile", "亲亲"),
            ("😋", "yum", "好吃 好吃馋"),
            ("😛", "tongue", "吐舌"),
            ("😜", "winking tongue", "吐舌 眨眼 顽皮"),
            ("🤪", "zany", "疯狂 搞怪"),
            ("😝", "squinting tongue", "吐舌 斗鸡眼"),
            ("🤑", "money mouth", "钱 贪财"),
            ("🤗", "hug", "拥抱"),
            ("🤭", "hand over mouth", "偷笑 掩嘴"),
            ("🤫", "shush", "嘘 安静 保密"),
            ("🤔", "thinking", "思考 想 考虑"),
            ("🤐", "zipper mouth", "闭嘴 保密"),
            ("🤨", "raised eyebrow", "怀疑 挑眉"),
            ("😐", "neutral", "无表情 平静"),
            ("😑", "expressionless", "无语 面无表情"),
            ("😶", "no mouth", "沉默 无嘴"),
            ("😏", "smirk", "得意 邪笑"),
            ("😒", "unamused", "不高兴 无语"),
            ("🙄", "rolling eyes", "翻白眼 无语"),
            ("😬", "grimacing", "龇牙 尴尬"),
            ("🤥", "lying", "说谎 匹诺曹"),
            ("😌", "relieved", "安心 舒服"),
            ("😔", "pensive", "沮丧 失落"),
            ("😪", "sleepy", "困 睡"),
            ("🤤", "drooling", "流口水 馋"),
            ("😴", "sleeping", "睡觉 睡着"),
            ("😷", "mask", "口罩 生病"),
            ("🤒", "thermometer", "发烧 生病"),
            ("🤕", "bandage", "受伤 包扎"),
            ("🤢", "nauseated", "恶心 吐"),
            ("🤮", "vomiting", "呕吐"),
            ("🤧", "sneezing", "打喷嚏 感冒"),
            ("🥵", "hot", "热 发烧"),
            ("🥶", "cold", "冷 冻"),
            ("🥴", "woozy", "醉 晕"),
            ("😵", "dizzy", "晕 头晕"),
            ("🤯", "exploding head", "爆炸 头大 震惊"),
            ("🤠", "cowboy", "牛仔"),
            ("🥳", "partying", "庆祝 派对"),
            ("😎", "sunglasses", "酷 墨镜"),
            ("🤓", "nerd", "书呆子 学霸"),
            ("🧐", "monocle", "考究 侦探"),
            ("😕", "confused", "困惑 不解"),
            ("😟", "worried", "担心 忧虑"),
            ("🙁", "frown", "皱眉 不高兴"),
            ("😮", "open mouth", "惊讶 张嘴"),
            ("😯", "hushed", "惊 哦"),
            ("😲", "astonished", "震惊 吃惊"),
            ("😳", "flushed", "脸红 尴尬"),
            ("🥺", "pleading", "恳求 委屈 可怜"),
            ("😦", "frowning open", "难过"),
            ("😧", "anguished", "痛苦 焦虑"),
            ("😨", "fearful", "害怕 恐惧"),
            ("😰", "anxious", "焦虑 冷汗"),
            ("😥", "sad relieved", "失望"),
            ("😢", "cry", "哭 哭泣"),
            ("😭", "sob", "大哭 泪崩"),
            ("😱", "scream", "尖叫 惊恐"),
            ("😖", "confounded", "纠结 难受"),
            ("😣", "persevere", "忍耐 坚持"),
            ("😞", "disappointed", "失望 沮丧"),
            ("😓", "downcast sweat", "失望 汗"),
            ("😩", "weary", "疲惫 累"),
            ("😫", "tired", "累 疲惫"),
            ("🥱", "yawning", "打哈欠 无聊"),
            ("😤", "triumph", "生气 愤怒"),
            ("😡", "rage", "愤怒 生气"),
            ("😠", "angry", "生气 愤怒"),
            ("🤬", "cursing", "骂人 脏话"),
            ("😈", "smiling imp", "恶魔 坏笑"),
            ("👿", "imp", "恶魔 恶鬼"),
            ("💀", "skull", "骷髅 死"),
            ("💩", "poop", "便便 大便"),
            ("🤡", "clown", "小丑"),
            ("👻", "ghost", "鬼 幽灵"),
            ("👽", "alien", "外星人"),
            ("🤖", "robot", "机器人"),
            ("😺", "smiling cat", "猫 笑"),
            ("😹", "cat joy", "猫 笑哭"),
            ("😻", "cat heart eyes", "猫 爱"),
            ("🙈", "see no evil", "捂眼 猴 不看"),
            ("🙉", "hear no evil", "捂耳 猴 不听"),
            ("🙊", "speak no evil", "捂嘴 猴 不说"),
            ("💋", "kiss mark", "吻 口红"),
            ("💘", "heart arrow", "心 爱心 丘比特"),
            ("❤️", "red heart", "心 红心 爱心 喜欢"),
            ("🧡", "orange heart", "橙心 爱心"),
            ("💛", "yellow heart", "黄心 爱心"),
            ("💚", "green heart", "绿心 爱心"),
            ("💙", "blue heart", "蓝心 爱心"),
            ("💜", "purple heart", "紫心 爱心"),
            ("🖤", "black heart", "黑心 爱心"),
            ("🤍", "white heart", "白心 爱心"),
            ("🤎", "brown heart", "棕心 爱心"),
            ("💔", "broken heart", "心碎 分手"),
            ("❣️", "heart exclamation", "心 感叹"),
            ("💕", "two hearts", "两颗心 爱"),
            ("💞", "revolving hearts", "旋转的心 爱"),
            ("💓", "beating heart", "跳动的心"),
            ("✨", "sparkles", "闪亮 星星 精彩"),
            ("⭐️", "star", "星 星星 收藏"),
            ("🌟", "glowing star", "闪星 星星"),
            ("💫", "dizzy star", "头晕 星星"),
            ("🔥", "fire", "火 热门 加油"),
            ("💥", "boom", "爆炸 撞击"),
            ("💯", "hundred", "一百分 满分"),
            ("⚡️", "zap", "闪电 电"),
            ("☀️", "sun", "太阳 晴"),
            ("🌙", "moon", "月亮 晚安"),
            ("🌈", "rainbow", "彩虹"),
            ("❄️", "snowflake", "雪花 冬 冷"),
            ("🎉", "tada", "庆祝 派对 撒花"),
            ("🎊", "confetti ball", "庆祝 撒花"),
            ("🎈", "balloon", "气球 派对"),
            ("🎁", "gift", "礼物 礼品"),
        ]
        list += smileys.map { EmojiDef(character: $0.0, name: $0.1, zh: $0.2, category: "smileys") }

        // 人物 People
        let people: [(String, String, String)] = [
            ("👍", "thumbs up", "赞 点赞 好"),
            ("👎", "thumbs down", "踩 不好 差"),
            ("👌", "ok hand", "好 OK"),
            ("🤌", "pinched fingers", "捏 什么"),
            ("✌️", "peace", "胜利 耶"),
            ("🤞", "crossed fingers", "祈祷 祝好运"),
            ("🤟", "love you", "爱你"),
            ("🤘", "rock on", "摇滚"),
            ("🤙", "call me", "打电话"),
            ("👈", "point left", "左 指向左"),
            ("👉", "point right", "右 指向右"),
            ("👆", "point up", "上 指向上"),
            ("👇", "point down", "下 指向下"),
            ("☝️", "index up", "第一 注意"),
            ("✋", "raised hand", "举手 手掌"),
            ("🤚", "raised back of hand", "手背"),
            ("🖐", "hand fingers splayed", "手掌 五"),
            ("🖖", "vulcan salute", "瓦肯 福长寿"),
            ("👋", "wave", "挥手 你好 再见"),
            ("🤝", "handshake", "握手 合作"),
            ("🙏", "pray", "祈祷 感谢 拜托"),
            ("✍️", "writing hand", "写 签名"),
            ("💪", "muscle", "肌肉 加油 强"),
            ("🦾", "mechanical arm", "机械臂 义肢"),
            ("🧠", "brain", "大脑 聪明"),
            ("👀", "eyes", "眼睛 看"),
            ("👁", "eye", "眼睛"),
            ("👄", "mouth", "嘴 嘴巴"),
            ("🦷", "tooth", "牙齿"),
            ("👅", "tongue", "舌头"),
            ("👶", "baby", "婴儿 宝宝"),
            ("🧒", "child", "孩子 儿童"),
            ("👦", "boy", "男孩"),
            ("👧", "girl", "女孩"),
            ("🧑", "person", "人"),
            ("👨", "man", "男人"),
            ("👩", "woman", "女人"),
            ("🧓", "older adult", "老人 长辈"),
            ("👨‍💻", "man technologist", "程序员 男 工程师"),
            ("👩‍💻", "woman technologist", "程序员 女 工程师"),
            ("👨‍🎓", "man student", "学生 男"),
            ("👩‍🎓", "woman student", "学生 女"),
            ("👨‍🏫", "man teacher", "老师 男"),
            ("👩‍🏫", "woman teacher", "老师 女"),
            ("👨‍⚕️", "man health worker", "医生 男"),
            ("👩‍⚕️", "woman health worker", "医生 女"),
            ("👨‍🍳", "man cook", "厨师 男"),
            ("👩‍🍳", "woman cook", "厨师 女"),
            ("🧑‍🚀", "astronaut", "宇航员 太空"),
            ("🕵️", "detective", "侦探"),
            ("💂", "guard", "卫兵"),
            ("🥷", "ninja", "忍者"),
            ("🧙", "mage", "法师 魔法"),
            ("🧚", "fairy", "仙女 精灵"),
            ("🧛", "vampire", "吸血鬼"),
            ("🧜", "merperson", "美人鱼"),
            ("🧟", "zombie", "僵尸"),
            ("🦸", "superhero", "超级英雄"),
            ("🦹", "supervillain", "超级反派"),
            ("🎅", "santa", "圣诞老人 圣诞"),
            ("🤶", "mrs claus", "圣诞奶奶"),
            ("👸", "princess", "公主"),
            ("🤴", "prince", "王子"),
            ("👰", "bride", "新娘 婚礼"),
            ("🤵", "groom", "新郎 婚礼"),
            ("💃", "dancing woman", "跳舞 舞蹈"),
            ("🕺", "dancing man", "跳舞 舞蹈"),
            ("👯", "dancing bunny ears", "兔耳 舞"),
            ("🚶", "walking", "走路 散步"),
            ("🏃", "running", "跑步 快"),
            ("🧗", "climbing", "攀岩 爬山"),
            ("🚴", "cycling", "骑车 自行车"),
            ("🧘", "lotus position", "冥想 瑜伽 打坐"),
            ("🛀", "bath", "洗澡 浴缸"),
            ("🛌", "sleeping bed", "睡觉 床"),
            ("👨‍👩‍👧", "family", "家庭 一家三口"),
            ("🫶", "heart hands", "比心 爱心"),
            ("🤲", "palms up", "摊手 接受"),
            ("👐", "open hands", "张开手 拥抱"),
            ("🙌", "raising hands", "举手 庆祝"),
            ("👏", "clap", "鼓掌 拍手"),
            ("🤝", "handshake 2", "握手"),
        ]
        list += people.map { EmojiDef(character: $0.0, name: $0.1, zh: $0.2, category: "people") }

        // 动物 Animals
        let animals: [(String, String, String)] = [
            ("🐶", "dog face", "狗 旺财 狗狗"),
            ("🐱", "cat face", "猫 喵 咪"),
            ("🐭", "mouse", "老鼠 鼠"),
            ("🐹", "hamster", "仓鼠"),
            ("🐰", "rabbit", "兔子 兔"),
            ("🦊", "fox", "狐狸"),
            ("🐻", "bear", "熊"),
            ("🐼", "panda", "熊猫"),
            ("🐨", "koala", "考拉 树袋熊"),
            ("🐯", "tiger", "老虎 虎"),
            ("🦁", "lion", "狮子"),
            ("🐮", "cow", "牛 奶牛"),
            ("🐷", "pig", "猪"),
            ("🐸", "frog", "青蛙 蛙"),
            ("🐵", "monkey", "猴子"),
            ("🙈", "monkey see no evil", "猴 捂眼"),
            ("🐔", "chicken", "鸡"),
            ("🐧", "penguin", "企鹅"),
            ("🐦", "bird", "鸟"),
            ("🐤", "baby chick", "小鸡 鸟"),
            ("🦆", "duck", "鸭子 鸭"),
            ("🦅", "eagle", "鹰 老鹰"),
            ("🦉", "owl", "猫头鹰"),
            ("🦇", "bat", "蝙蝠"),
            ("🐺", "wolf", "狼"),
            ("🐗", "boar", "野猪"),
            ("🐴", "horse", "马"),
            ("🦄", "unicorn", "独角兽"),
            ("🐝", "bee", "蜜蜂 蜂"),
            ("🐛", "bug", "虫 毛毛虫"),
            ("🦋", "butterfly", "蝴蝶"),
            ("🐌", "snail", "蜗牛"),
            ("🐞", "lady beetle", "瓢虫"),
            ("🐜", "ant", "蚂蚁"),
            ("🕷", "spider", "蜘蛛"),
            ("🦂", "scorpion", "蝎子"),
            ("🐢", "turtle", "乌龟 海龟"),
            ("🐍", "snake", "蛇"),
            ("🦎", "lizard", "蜥蜴"),
            ("🐙", "octopus", "章鱼"),
            ("🦑", "squid", "鱿鱼"),
            ("🦐", "shrimp", "虾"),
            ("🦀", "crab", "螃蟹"),
            ("🐡", "blowfish", "河豚 鱼"),
            ("🐠", "tropical fish", "热带鱼 鱼"),
            ("🐟", "fish", "鱼"),
            ("🐬", "dolphin", "海豚"),
            ("🐳", "whale", "鲸鱼"),
            ("🦈", "shark", "鲨鱼"),
            ("🐊", "crocodile", "鳄鱼"),
            ("🐅", "tiger 2", "虎"),
            ("🦓", "zebra", "斑马"),
            ("🦍", "gorilla", "大猩猩"),
            ("🐘", "elephant", "大象 象"),
            ("🦛", "hippopotamus", "河马"),
            ("🦏", "rhinoceros", "犀牛"),
            ("🐪", "camel", "骆驼"),
            ("🦒", "giraffe", "长颈鹿"),
            ("🦘", "kangaroo", "袋鼠"),
            ("🐄", "cow 2", "奶牛"),
            ("🐑", "sheep", "羊 绵羊"),
            ("🐐", "goat", "山羊"),
            ("🦌", "deer", "鹿"),
            ("🐕", "dog", "狗"),
            ("🐩", "poodle", "贵宾犬"),
            ("🐈", "cat", "猫"),
            ("🐓", "rooster", "公鸡"),
            ("🦃", "turkey", "火鸡"),
            ("🦚", "peacock", "孔雀"),
            ("🦜", "parrot", "鹦鹉"),
            ("🦢", "swan", "天鹅"),
            ("🐇", "rabbit 2", "兔"),
            ("🦝", "raccoon", "浣熊"),
            ("🦨", "skunk", "臭鼬"),
            ("🦡", "badger", "獾"),
            ("🦦", "otter", "水獭"),
            ("🦥", "sloth", "树懒"),
            ("🐁", "mouse 2", "鼠"),
            ("🐀", "rat", "大鼠"),
            ("🐿", "chipmunk", "松鼠"),
            ("🦔", "hedgehog", "刺猬"),
            ("🐾", "paw prints", "爪印 脚印"),
            ("🐉", "dragon", "龙"),
            ("🐲", "dragon face", "龙"),
        ]
        list += animals.map { EmojiDef(character: $0.0, name: $0.1, zh: $0.2, category: "animals") }

        // 食物 Food
        let food: [(String, String, String)] = [
            ("🍏", "green apple", "苹果 青苹果"),
            ("🍎", "red apple", "苹果 红苹果"),
            ("🍐", "pear", "梨"),
            ("🍊", "orange", "橙子 橘子"),
            ("🍋", "lemon", "柠檬"),
            ("🍌", "banana", "香蕉"),
            ("🍉", "watermelon", "西瓜"),
            ("🍇", "grapes", "葡萄"),
            ("🍓", "strawberry", "草莓"),
            ("🫐", "blueberries", "蓝莓"),
            ("🍈", "melon", "瓜 甜瓜"),
            ("🍒", "cherries", "樱桃 车厘子"),
            ("🍑", "peach", "桃子 桃"),
            ("🥭", "mango", "芒果"),
            ("🍍", "pineapple", "菠萝 凤梨"),
            ("🥥", "coconut", "椰子"),
            ("🥝", "kiwi", "猕猴桃 奇异果"),
            ("🍅", "tomato", "西红柿 番茄"),
            ("🍆", "eggplant", "茄子"),
            ("🥑", "avocado", "牛油果"),
            ("🥦", "broccoli", "西兰花"),
            ("🥬", "leafy green", "青菜 白菜"),
            ("🥒", "cucumber", "黄瓜"),
            ("🌶", "hot pepper", "辣椒"),
            ("🌽", "corn", "玉米"),
            ("🥕", "carrot", "胡萝卜"),
            ("🧄", "garlic", "大蒜"),
            ("🧅", "onion", "洋葱"),
            ("🥔", "potato", "土豆 马铃薯"),
            ("🍠", "roasted sweet potato", "红薯 地瓜"),
            ("🥐", "croissant", "牛角面包 可颂"),
            ("🍞", "bread", "面包"),
            ("🥖", "baguette", "法棍"),
            ("🥨", "pretzel", "椒盐卷饼"),
            ("🧀", "cheese", "奶酪 芝士"),
            ("🥚", "egg", "鸡蛋 蛋"),
            ("🍳", "cooking", "煎蛋 做饭"),
            ("🧈", "butter", "黄油"),
            ("🥞", "pancakes", "煎饼 松饼"),
            ("🧇", "waffle", "华夫饼"),
            ("🥓", "bacon", "培根"),
            ("🥩", "steak", "牛排"),
            ("🍗", "poultry leg", "鸡腿 鸡肉"),
            ("🍖", "meat on bone", "肉 排骨"),
            ("🌭", "hot dog", "热狗"),
            ("🍔", "hamburger", "汉堡 汉堡包"),
            ("🍟", "fries", "薯条"),
            ("🍕", "pizza", "披萨"),
            ("🥪", "sandwich", "三明治"),
            ("🥙", "stuffed flatbread", "卷饼"),
            ("🌮", "taco", "塔可 墨西哥卷"),
            ("🌯", "burrito", "墨西哥卷饼"),
            ("🥗", "salad", "沙拉"),
            ("🥘", "paella", "炖饭"),
            ("🍜", "ramen", "拉面 面条"),
            ("🍲", "stew", "炖汤 砂锅"),
            ("🍛", "curry", "咖喱 咖喱饭"),
            ("🍣", "sushi", "寿司"),
            ("🍱", "bento", "便当"),
            ("🥟", "dumpling", "饺子"),
            ("🍤", "fried shrimp", "虾 天妇罗"),
            ("🍚", "rice", "米饭"),
            ("🍙", "rice ball", "饭团"),
            ("🍘", "rice cracker", "米饼"),
            ("🍜", "noodles", "面条 面"),
            ("🍢", "oden", "关东煮"),
            ("🍡", "dango", "团子"),
            ("🍧", "shaved ice", "刨冰"),
            ("🍨", "ice cream", "冰淇淋 雪糕"),
            ("🍦", "soft ice cream", "甜筒"),
            ("🥧", "pie", "派 馅饼"),
            ("🍰", "cake", "蛋糕"),
            ("🧁", "cupcake", "纸杯蛋糕"),
            ("🎂", "birthday cake", "生日蛋糕"),
            ("🍮", "custard", "布丁"),
            ("🍭", "lollipop", "棒棒糖"),
            ("🍬", "candy", "糖果"),
            ("🍫", "chocolate", "巧克力"),
            ("🍿", "popcorn", "爆米花"),
            ("🍩", "doughnut", "甜甜圈"),
            ("🍪", "cookie", "曲奇 饼干"),
            ("☕️", "coffee", "咖啡"),
            ("🍵", "tea", "茶 绿茶"),
            ("🧋", "bubble tea", "奶茶 珍珠奶茶"),
            ("🥤", "cup straw", "饮料 汽水"),
            ("🍺", "beer", "啤酒"),
            ("🍻", "beers", "干杯 啤酒"),
            ("🍷", "wine", "红酒 葡萄酒"),
            ("🥂", "clink glasses", "干杯 庆祝"),
            ("🥃", "tumbler", "威士忌"),
            ("🍶", "sake", "清酒"),
            ("🧊", "ice", "冰 冰块"),
            ("🥢", "chopsticks", "筷子"),
            ("🍽", "plate", "餐盘 用餐"),
        ]
        list += food.map { EmojiDef(character: $0.0, name: $0.1, zh: $0.2, category: "food") }

        // 活动 Activity
        let activity: [(String, String, String)] = [
            ("⚽️", "soccer", "足球"),
            ("🏀", "basketball", "篮球"),
            ("🏈", "football", "橄榄球"),
            ("⚾️", "baseball", "棒球"),
            ("🎾", "tennis", "网球"),
            ("🏐", "volleyball", "排球"),
            ("🎱", "8 ball", "台球"),
            ("🏓", "ping pong", "乒乓球"),
            ("🏸", "badminton", "羽毛球"),
            ("🥊", "boxing glove", "拳击"),
            ("⛷", "skier", "滑雪"),
            ("🏂", "snowboarder", "单板滑雪"),
            ("🏋️", "weight lifting", "举重 健身"),
            ("🤸", "cartwheel", "侧手翻"),
            ("🎯", "dart", "目标 飞镖"),
            ("🎮", "game controller", "游戏 游戏 手柄"),
            ("🎲", "dice", "骰子"),
            ("🧩", "puzzle", "拼图"),
            ("🎨", "art", "艺术 画画 调色板"),
            ("🎬", "clapper", "电影 拍摄"),
            ("🎤", "microphone", "麦克风 唱歌"),
            ("🎧", "headphone", "耳机 音乐"),
            ("🎼", "musical score", "乐谱"),
            ("🎹", "piano", "钢琴"),
            ("🥁", "drum", "鼓"),
            ("🎷", "saxophone", "萨克斯"),
            ("🎺", "trumpet", "小号"),
            ("🎸", "guitar", "吉他"),
            ("🎻", "violin", "小提琴"),
            ("🏆", "trophy", "奖杯 冠军"),
            ("🥇", "gold medal", "金牌 第一"),
            ("🥈", "silver medal", "银牌 第二"),
            ("🥉", "bronze medal", "铜牌 第三"),
            ("🎫", "ticket", "票 门票"),
            ("🎪", "circus", "马戏团"),
            ("🎭", "theater", "戏剧"),
            ("🖼", "frame", "画框"),
            ("🧵", "thread", "线 缝纫"),
            ("🪡", "sewing needle", "针"),
        ]
        list += activity.map { EmojiDef(character: $0.0, name: $0.1, zh: $0.2, category: "activity") }

        // 旅行 Travel
        let travel: [(String, String, String)] = [
            ("🚗", "car", "汽车 车"),
            ("🚕", "taxi", "出租车 的士"),
            ("🚙", "suv", "越野车"),
            ("🚌", "bus", "公交车 巴士"),
            ("🏎", "race car", "赛车"),
            ("🚓", "police car", "警车"),
            ("🚑", "ambulance", "救护车"),
            ("🚒", "fire engine", "消防车"),
            ("🚚", "truck", "卡车 货车"),
            ("🚜", "tractor", "拖拉机"),
            ("🛴", "scooter", "滑板车"),
            ("🚲", "bicycle", "自行车"),
            ("🛵", "motor scooter", "摩托车 电动车"),
            ("✈️", "airplane", "飞机"),
            ("🚀", "rocket", "火箭 发射"),
            ("🛸", "ufo", "飞碟"),
            ("🚁", "helicopter", "直升机"),
            ("⛵️", "sailboat", "帆船"),
            ("🚢", "ship", "轮船"),
            ("🗺", "world map", "地图"),
            ("🧭", "compass", "指南针"),
            ("🏔", "mountain", "山 雪山"),
            ("🌋", "volcano", "火山"),
            ("🏕", "camping", "露营 帐篷"),
            ("🏖", "beach", "海滩 沙滩"),
            ("🏜", "desert", "沙漠"),
            ("🏝", "island", "岛屿"),
            ("🌇", "sunset", "日落 黄昏"),
            ("🌆", "cityscape dusk", "城市 夜晚"),
            ("🏙", "cityscape", "城市 楼群"),
            ("🌃", "night stars", "星空 夜晚"),
            ("🌉", "bridge night", "大桥"),
            ("🎡", "ferris wheel", "摩天轮"),
            ("🎢", "roller coaster", "过山车"),
            ("🎪", "circus 2", "马戏"),
            ("Station", "placeholder", "占位忽略"),
            ("🏢", "office", "办公楼 公司"),
            ("🏥", "hospital", "医院"),
            ("🏦", "bank", "银行"),
            ("🏨", "hotel", "酒店 宾馆"),
            ("🏪", "convenience store", "便利店"),
            ("🏫", "school", "学校"),
            ("🌍", "globe", "地球 世界"),
            ("🌏", "globe asia", "地球 亚洲"),
            ("🕯", "candle", "蜡烛"),
            ("🚦", "traffic light", "红绿灯"),
            ("🏠", "house", "房子 家"),
            ("🏢", "office 2", "办公室"),
        ]
        list += travel.filter { $0.0 != "Station" }
            .map { EmojiDef(character: $0.0, name: $0.1, zh: $0.2, category: "travel") }

        // 物品 Objects
        let objects: [(String, String, String)] = [
            ("⌚️", "watch", "手表 时间"),
            ("📱", "phone", "手机 电话"),
            ("💻", "laptop", "电脑 笔记本"),
            ("🖥", "desktop", "台式机 电脑"),
            ("⌨️", "keyboard", "键盘"),
            ("🖱", "mouse 3", "鼠标"),
            ("🖨", "printer", "打印机"),
            ("💾", "floppy disk", "软盘 保存"),
            ("💿", "cd", "光盘"),
            ("📷", "camera", "相机 拍照"),
            ("📹", "video camera", "摄像机"),
            ("🎥", "movie camera", "电影机"),
            ("📺", "tv", "电视"),
            ("📻", "radio", "收音机"),
            ("⏰", "alarm clock", "闹钟"),
            ("⏳", "hourglass", "沙漏 时间"),
            ("🔋", "battery", "电池 电量"),
            ("🔌", "plug", "插头 电源"),
            ("💡", "bulb", "灯泡 想法 主意"),
            ("🔦", "flashlight", "手电筒"),
            ("🕯", "candle 2", "蜡烛"),
            ("🧯", "fire extinguisher", "灭火器"),
            ("🛢", "oil drum", "油桶"),
            ("💸", "money wings", "花钱 钞票"),
            ("💵", "dollar", "美元 钱"),
            ("💴", "yen", "日元 钱"),
            ("💶", "euro", "欧元 钱"),
            ("💷", "pound", "英镑 钱"),
            ("💰", "money bag", "钱袋 金钱"),
            ("💳", "credit card", "信用卡 银行卡"),
            ("💎", "gem", "钻石 宝石"),
            ("⚖️", "balance", "天平 法律 公平"),
            ("🔧", "wrench", "扳手 修理 工具"),
            ("🔨", "hammer", "锤子 敲打"),
            ("⛏", "pick", "镐 挖"),
            ("🔩", "nut and bolt", "螺丝"),
            ("⚙️", "gear", "齿轮 设置"),
            ("🧰", "toolbox", "工具箱"),
            ("🧲", "magnet", "磁铁"),
            ("🔫", "water pistol", "枪 水枪"),
            ("💣", "bomb", "炸弹 爆炸"),
            ("🔪", "knife", "刀"),
            ("🛡", "shield", "盾牌 防护"),
            ("🚬", "smoking", "吸烟 香烟"),
            ("⚰️", "coffin", "棺材"),
            ("🔮", "crystal ball", "水晶球 预言"),
            ("📿", "prayer beads", "念珠"),
            ("🧿", "nazar", "护身符 眼睛"),
            ("💈", "barber", "理发店"),
            ("🔭", "telescope", "望远镜"),
            ("🔬", "microscope", "显微镜"),
            ("🕳", "hole", "洞"),
            ("💊", "pill", "药 药丸"),
            ("💉", "syringe", "注射 打针"),
            ("🩹", "adhesive bandage", "创可贴"),
            ("🩺", "stethoscope", "听诊器 医生"),
            ("🚪", "door", "门"),
            ("🛏", "bed", "床"),
            ("🚽", "toilet", "马桶 厕所"),
            ("🚿", "shower", "淋浴"),
            ("🧴", "lotion", "乳液"),
            ("🧷", "safety pin", "别针"),
            ("🧹", "broom", "扫帚 打扫"),
            ("🧺", "basket", "篮子"),
            ("🧻", "roll of paper", "纸 卷纸"),
            ("🧼", "soap", "肥皂 洗手"),
            ("🧽", "sponge", "海绵"),
            ("🧯", "extinguisher", "灭火器"),
            ("🛒", "shopping cart", "购物车"),
            (" unpaid", "placeholder", "占位忽略"),
            ("📌", "pushpin", "图钉 固定 置顶"),
            ("📍", "round pushpin", "定位 位置"),
            ("📎", "paperclip", "回形针 附件"),
            ("🖇", "paperclips", "回形针"),
            ("📏", "ruler", "尺子"),
            ("📐", "triangle ruler", "三角尺"),
            ("✂️", "scissors", "剪刀 剪切"),
            ("🗃", "card box", "卡片盒 档案"),
            ("🗄", "file cabinet", "文件柜"),
            ("🗑", "wastebasket", "垃圾桶 废纸篓"),
            ("🔒", "lock", "锁 锁定 加密"),
            ("🔓", "unlock", "解锁"),
            ("🔑", "key", "钥匙 密钥"),
            ("🔨", "hammer 2", "锤子"),
            ("🛠", "hammer wrench", "工具"),
            ("📨", "envelope arrow", "来信 收件"),
            ("📧", "email", "邮件 email"),
            ("📥", "inbox tray", "收件箱"),
            ("📤", "outbox tray", "发件箱"),
            ("📦", "package", "包裹 包装箱"),
            ("🏷", "label", "标签"),
            ("📝", "memo", "备忘 记录 笔记"),
            ("📚", "books", "书 图书 学习"),
            ("📖", "open book", "书 阅读"),
            ("📒", "notebook", "笔记本"),
            ("📃", "page curl", "文件 页"),
            ("📄", "page", "文档 文件"),
            ("📅", "calendar", "日历 日期"),
            ("📆", "tear off calendar", "日历"),
            ("🗓", "spiral calendar", "日历"),
            ("📇", "card index", "名片 索引"),
            ("📈", "chart up", "图表 上升 增长"),
            ("📉", "chart down", "图表 下降"),
            ("📊", "bar chart", "柱状图 数据"),
            ("📋", "clipboard", "剪贴板 列表 清单"),
            ("📌", "pin 2", "图钉"),
            ("📁", "folder", "文件夹"),
            ("📂", "open folder", "打开的文件夹"),
            ("🗂", "dividers", "文件夹 分类"),
            ("🗞", "newspaper roll", "报纸"),
            ("📰", "newspaper", "报纸 新闻"),
            ("📓", "notebook deco", "笔记本"),
            ("📔", "notebook heart", "笔记本"),
            ("📕", "closed book", "书"),
            ("📗", "green book", "书"),
            ("📘", "blue book", "书"),
            ("📙", "orange book", "书"),
        ]
        list += objects.filter { !$0.0.hasPrefix(" ") }
            .map { EmojiDef(character: $0.0, name: $0.1, zh: $0.2, category: "objects") }

        // 符号 Symbols
        let symbols: [(String, String, String)] = [
            ("©", "copyright", "版权"),
            ("®", "registered", "注册商标"),
            ("™", "trademark", "商标"),
            ("§", "section", "章节"),
            ("¶", "paragraph", "段落"),
            ("†", "dagger", "剑标"),
            ("‡", "double dagger", "双剑标"),
            ("•", "bullet", "圆点 项目符号"),
            ("…", "ellipsis", "省略号"),
            ("‰", "per mille", "千分号"),
            ("€", "euro sign", "欧元"),
            ("£", "pound sign", "英镑"),
            ("¥", "yen sign", "人民币 日元"),
            ("¢", "cent", "美分"),
            ("°", "degree", "度 温度"),
            ("±", "plus minus", "正负 加减"),
            ("×", "multiply", "乘号 叉"),
            ("÷", "divide", "除号"),
            ("≈", "almost equal", "约等于"),
            ("≠", "not equal", "不等于"),
            ("≤", "less equal", "小于等于"),
            ("≥", "greater equal", "大于等于"),
            ("√", "sqrt", "根号"),
            ("∞", "infinity", "无穷 无限"),
            ("∑", "sum", "求和"),
            ("∏", "product", "求积"),
            ("∫", "integral", "积分"),
            ("µ", "micro", "微"),
            ("π", "pi", "圆周率 派"),
            ("Ω", "omega", "欧姆"),
            ("←", "left arrow", "左箭头"),
            ("→", "right arrow", "右箭头 右"),
            ("↑", "up arrow", "上箭头 上"),
            ("↓", "down arrow", "下箭头 下"),
            ("↔", "left right arrow", "左右箭头"),
            ("↵", "return arrow", "回车"),
            ("⇧", "shift", "上档键 shift"),
            ("⌘", "command", "command 键 花键"),
            ("⌥", "option", "option 键 alt"),
            ("⌃", "control", "control 键 ctrl"),
            ("⌫", "delete left", "删除键 退格"),
            ("⎋", "escape", "esc 退出键"),
            ("⏎", "return key", "回车键 return"),
            ("␣", "space", "空格"),
            ("✓", "check", "对 勾 完成"),
            ("✔", "check heavy", "对 完成"),
            ("✗", "cross", "错 叉"),
            ("✘", "cross heavy", "错"),
            ("★", "star outline", "星 五角星"),
            ("☆", "star empty", "星 空星"),
            ("♡", "heart outline", "心 爱心"),
            ("♥", "heart solid", "心 爱心"),
            ("♦", "diamond", "方块 菱形"),
            ("♣", "club", "梅花"),
            ("♠", "spade", "黑桃"),
            ("♪", "note", "音符 音乐"),
            ("♫", "notes", "音符 音乐"),
            ("☀", "sun sign", "太阳"),
            ("☁", "cloud", "云 多云"),
            ("☂", "umbrella", "伞 下雨"),
            ("☃", "snowman", "雪人"),
            ("⌚", "watch sign", "表"),
            ("☰", "hamburger", "菜单 三横"),
            ("⋮", "vertical ellipsis", "竖省略 更多"),
            ("⋯", "midline ellipsis", "省略号"),
            ("«", "guillemet left", "左书名号"),
            ("»", "guillemet right", "右书名号"),
            ("¿", "inverted question", "倒问号"),
            ("¡", "inverted exclamation", "倒叹号"),
        ]
        list += symbols.map { EmojiDef(character: $0.0, name: $0.1, zh: $0.2, category: "symbols") }

        return list
    }
}
